overrides:
  bin-wrapper: npm:bin-wrapper-china
  unconfig: 7.3.2

onlyBuiltDependencies:
  - '@swc/core'
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - es5-ext
  - esbuild
  - less
  - protobufjs
  - vue-demi

allowBuilds:
  '@swc/core': true
  '@uni-helper/unocss-preset-uni': true
  core-js: true
  es5-ext: true
  esbuild: true
  less: true
  protobufjs: true
  vue-demi: true
